"""empty message

Revision ID: 293d09353ea3
Revises: a94ab697a427
Create Date: 2024-08-17 18:26:09.942445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '293d09353ea3'
down_revision: Union[str, None] = 'a94ab697a427'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_crypto_asset_quotes_asset_uuid', table_name='crypto_asset_quotes')
    op.create_index(op.f('ix_crypto_asset_quotes_asset_uuid'), 'crypto_asset_quotes', ['asset_uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crypto_asset_quotes_asset_uuid'), table_name='crypto_asset_quotes')
    op.create_index('ix_crypto_asset_quotes_asset_uuid', 'crypto_asset_quotes', ['asset_uuid'], unique=False)
    # ### end Alembic commands ###
