"""empty message

Revision ID: 91af64d584c8
Revises: e8af8023e382
Create Date: 2024-07-29 20:05:26.882746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91af64d584c8'
down_revision: Union[str, None] = 'e8af8023e382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_chats',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tg_id', sa.NUMERIC(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('fullname', sa.String(), nullable=True),
    sa.Column('is_forum', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('bio', sa.String(), nullable=False),
    sa.Column('join_by_request', sa.Boolean(), nullable=False),
    sa.Column('invite_link', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_index(op.f('ix_tg_chats_type'), 'tg_chats', ['type'], unique=False)
    op.create_index(op.f('ix_tg_chats_username'), 'tg_chats', ['username'], unique=False)
    op.create_table('tg_users',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tg_id', sa.NUMERIC(), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('language_code', sa.String(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('added_to_attachment_menu', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('tg_chats_to_users',
    sa.Column('tg_chat', sa.UUID(), nullable=False),
    sa.Column('tg_user', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tg_chat'], ['tg_chats.uuid'], ),
    sa.ForeignKeyConstraint(['tg_user'], ['tg_users.uuid'], ),
    sa.PrimaryKeyConstraint('tg_chat', 'tg_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tg_chats_to_users')
    op.drop_table('tg_users')
    op.drop_index(op.f('ix_tg_chats_username'), table_name='tg_chats')
    op.drop_index(op.f('ix_tg_chats_type'), table_name='tg_chats')
    op.drop_table('tg_chats')
    # ### end Alembic commands ###
