"""empty message

Revision ID: b49792bf231d
Revises: 0a9d8083df48
Create Date: 2024-07-25 11:18:06.516345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b49792bf231d'
down_revision: Union[str, None] = '0a9d8083df48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binance_crypto_trading_pairs',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('base_asset_uuid', sa.UUID(), nullable=False),
    sa.Column('base_asset_ticker', sa.String(), nullable=False),
    sa.Column('quote_asset_uuid', sa.UUID(), nullable=False),
    sa.Column('quote_asset_ticker', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('iceberg_allowed', sa.Boolean(), nullable=False),
    sa.Column('oco_allowed', sa.Boolean(), nullable=False),
    sa.Column('oto_allowed', sa.Boolean(), nullable=False),
    sa.Column('quote_order_qty_market_allowed', sa.Boolean(), nullable=False),
    sa.Column('allow_trailing_stop', sa.Boolean(), nullable=False),
    sa.Column('cancel_replace_allowed', sa.Boolean(), nullable=False),
    sa.Column('is_spot_trading_allowed', sa.Boolean(), nullable=False),
    sa.Column('is_margin_trading_allowed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_asset_uuid'], ['binance_crypto_assets.uuid'], ),
    sa.ForeignKeyConstraint(['quote_asset_uuid'], ['binance_crypto_assets.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('base_asset_uuid', 'quote_asset_uuid', name='unique_from_to_asset_pair')
    )
    op.create_index(op.f('ix_binance_crypto_trading_pairs_base_asset_ticker'), 'binance_crypto_trading_pairs', ['base_asset_ticker'], unique=False)
    op.create_index(op.f('ix_binance_crypto_trading_pairs_quote_asset_ticker'), 'binance_crypto_trading_pairs', ['quote_asset_ticker'], unique=False)
    op.add_column('binance_crypto_assets', sa.Column('seq_num', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_binance_crypto_assets_seq_num'), 'binance_crypto_assets', ['seq_num'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_binance_crypto_assets_seq_num'), table_name='binance_crypto_assets')
    op.drop_column('binance_crypto_assets', 'seq_num')
    op.drop_index(op.f('ix_binance_crypto_trading_pairs_quote_asset_ticker'), table_name='binance_crypto_trading_pairs')
    op.drop_index(op.f('ix_binance_crypto_trading_pairs_base_asset_ticker'), table_name='binance_crypto_trading_pairs')
    op.drop_table('binance_crypto_trading_pairs')
    # ### end Alembic commands ###
