"""empty message

Revision ID: 4610160f2868
Revises: b49792bf231d
Create Date: 2024-07-28 18:44:25.232665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4610160f2868'
down_revision: Union[str, None] = 'b49792bf231d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_asset_tags',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('crypto_assets',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('cmc_date_added', sa.TIMESTAMP(), nullable=False),
    sa.Column('num_market_pairs', sa.Integer(), nullable=False),
    sa.Column('infinite_supply', sa.Boolean(), nullable=False),
    sa.Column('max_supply', sa.String(), nullable=True),
    sa.Column('cmc_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('cmc_id')
    )
    op.create_index(op.f('ix_crypto_assets_name'), 'crypto_assets', ['name'], unique=False)
    op.create_index(op.f('ix_crypto_assets_slug'), 'crypto_assets', ['slug'], unique=False)
    op.create_index(op.f('ix_crypto_assets_ticker'), 'crypto_assets', ['ticker'], unique=False)
    op.create_table('crypto_asset_quotes',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('asset_uuid', sa.UUID(), nullable=False),
    sa.Column('cmc_last_updated', sa.TIMESTAMP(), nullable=False),
    sa.Column('market_cap_dominance', sa.NUMERIC(precision=30, scale=4), nullable=False),
    sa.Column('percent_change_30d', sa.NUMERIC(precision=30, scale=4), nullable=False),
    sa.Column('percent_change_1h', sa.NUMERIC(precision=30, scale=4), nullable=False),
    sa.Column('percent_change_24h', sa.NUMERIC(precision=30, scale=4), nullable=False),
    sa.Column('percent_change_7d', sa.NUMERIC(precision=30, scale=4), nullable=False),
    sa.Column('percent_change_60d', sa.NUMERIC(precision=30, scale=4), nullable=False),
    sa.Column('percent_change_90d', sa.NUMERIC(precision=30, scale=4), nullable=False),
    sa.Column('market_cap', sa.NUMERIC(precision=30, scale=4), nullable=False),
    sa.Column('volume_change_24h', sa.NUMERIC(precision=30, scale=4), nullable=False),
    sa.Column('volume_24h', sa.NUMERIC(precision=30, scale=4), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=30, scale=4), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_uuid'], ['crypto_assets.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crypto_asset_quotes_asset_uuid'), 'crypto_asset_quotes', ['asset_uuid'], unique=False)
    op.create_table('crypto_assets_to_asset_tags',
    sa.Column('asset_uuid', sa.UUID(), nullable=False),
    sa.Column('tag_uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_uuid'], ['crypto_assets.uuid'], ),
    sa.ForeignKeyConstraint(['tag_uuid'], ['crypto_asset_tags.uuid'], ),
    sa.PrimaryKeyConstraint('asset_uuid', 'tag_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crypto_assets_to_asset_tags')
    op.drop_index(op.f('ix_crypto_asset_quotes_asset_uuid'), table_name='crypto_asset_quotes')
    op.drop_table('crypto_asset_quotes')
    op.drop_index(op.f('ix_crypto_assets_ticker'), table_name='crypto_assets')
    op.drop_index(op.f('ix_crypto_assets_slug'), table_name='crypto_assets')
    op.drop_index(op.f('ix_crypto_assets_name'), table_name='crypto_assets')
    op.drop_table('crypto_assets')
    op.drop_table('crypto_asset_tags')
    # ### end Alembic commands ###
